### PR TITLE
Modified helpers.js, swagger-metadata.js added body flag to convertValue so it will not convert to an array if the body is object

### PR DESCRIPTION
**Pull request by fastcodejava**
Ref : https://github.com/apigee-127/swagger-tools/issues/438

### CODE REVIEW

**Comment by SameerSiddiqui** [comment]
Seems like this fix will work and will be more clear!

**Comment by whitlockjc** [comment]
I don't agree with this implementation.  All that should be required is to update `lib/middleware/helpers.java#convertValue` to not convert `Object` values to a single-item `Array` for `body` parameter types.  Fixing that should be enough because the type validation that happens after converting a value should trigger the proper error.

As I mentioned in #438, I couldn't work on this until today _(I was gone on vacation)_.  I will get a fix for this out today.

**Comment by fastcodejava** [comment]
@whitlockjc I did that first but I had some problem.
The problem is there's a call to map which is messing up the payload. 
I hope you understand.

**Comment by whitlockjc** [comment]
I'll fix this tonight, the commit will be referenced from #438.  We'll compare then.

**Pull request closed without merging**
