### PR TITLE
Update static files of swaggerUi

### PR DESCRIPTION
**Pull request by mikspi**
The swaggerUi dependency injected in the repo looks like old. For instance, it doesn't have this commit `https://github.com/swagger-api/swagger-ui/pull/2014` which solves this auth issue `https://github.com/swagger-api/swagger-ui/issues/1108`, useful to authenticate the calls through a Bearer token.

This pull request updates the swaggerUi folder and it also tweak the index.html in order to get the swagger doc from the header field "Swagger-API-Docs-URL".

### CODE REVIEW

**Comment by whitlockjc** [comment]
I haven't had a chance to check the changes out to `index.html` to retrieve the `Swagger-API-Docs-URL` but did it follow the same approach we have been?  I really hate having to do this but I've no better idea.

**Comment by mikspi** [comment]
Yes it does and I hated it too, because every time we want to update the swaggerUi dependency it is a mess! I spent a bit trying to pass the doc url in a nicer way, but the dependency serve-static doesn't help...

**Comment by whitlockjc** [comment]
Agreed.  It's not pretty but without it, swagger-ui doesn't really lend itself to handling things like this itself.

**Comment by whitlockjc** [comment]
I'm going to merge this after I release a new version of json-refs here in the next few days.

**Comment by mikspi** [comment]
👍

**Comment by mikspi** [comment]
Hi @whitlockjc, will you merge this?

**Comment by whitlockjc** [comment]
Sure.  I was on vacation last week so I apologize for the slow response.

**Comment by mikspi** [comment]
Hi @whitlockjc I was just wondering what is the status of this pull request

**Comment by FieryCod** [comment]
@whitlockjc I am sorry, but I am wondering why this PR is not merged?

**Comment by whitlockjc** [comment]
Because by the time I merge it, it will be out of date.  I am holding off on updating `swagger-ui` until right before release time.

**Comment by FieryCod** [comment]
Ok that makes sense thank you. When do you plan to release current version to npm?

**Comment by whitlockjc** [comment]
I'm not sure honestly.  I'm knee-deep in a rewrite of `json-refs` to fix a number of performance issues and bugs.  Once that's done, I will update `sway` to use it _(fixing its bugs)_ and do the same with `swagger-tools`.

**Comment by miguelduarte42** [comment]
There's a new version of `swagger-ui` (v3). Wouldn't it be possible to include SwaggerUI as a dependency of `swagger-tools` instead of having to copy the files to this project? It would make it easier to update it to recent versions. Better yet, being able to pass a `swagger-ui` reference as a configuration parameter would allow the end-user to use whatever version of `swagger-ui` he/she wants.

**Comment by whitlockjc** [comment]
Yep, already taken care of.  As for why we do it this way, we are up the details automatically so that `swagger-ui` can find your API and such.  It's definitely a pain having to do it this way.  I'm all ears.

**Comment by whitlockjc** [comment]
Done as part of 9b5131361ec75712a6a0784b2e106d7664eb5b4f

**Pull request closed without merging**
