### PR TITLE
issue 428: date-time validator rejects value with Z suffix

### PR DESCRIPTION
**Pull request by mattoshry**
Description of defect at https://github.com/apigee-127/swagger-tools/issues/428

### CODE REVIEW

**Comment by whitlockjc** [comment]
Do you mind running `npm test` and appending the commit with the browser binaries built in `browser`?  I _think_ this should regenerate those.  Other than that, great job.

**Comment by mattoshry** [comment]
Updated with browser-compatible packages, @whitlockjc. Mind merging?

**Comment by whitlockjc** [comment]
I think the try/catch was there on purpose to make the API return `false` whenever it failed to parse the offset hours/minutes.  I think we should keep that as-is to avoid any breakages.  Thoughts?

**Comment by mattoshry** [comment]
I couldn't figure out what value would cause Number to throw. At worst it should return NaN.

**Comment by mattoshry** [comment]
The value in matches[6] and matches[7] will be `undefined` or a string. Acc. 7.1.3 of ECMA-262, the former will always produce NaN. The rules for the latter are more complicated, but it won't throw. At worst, it should be NaN, and that will tickle the return on line 125.

**Comment by whitlockjc** [comment]
Thanks for looking into this.  :)

**Pull request merged**
