### PR TITLE
Allow streaming data to the res object and still perform validation.

### PR DESCRIPTION
**Pull request by SandyChapman**
This PR fixes a case where we want to make a controller proxy a request to another endpoint utilizing the write stream capabilities of the res object. I.e. if we had the following controller, where we're using the pipe, originally, the endpoint would not be validated. This is because the "write" callback is not being wrapped and thus the "data" parameter is null once the wrapped "end" call is made which prevents any validation from happening.

Example code:

```
'use strict';

var request = require('request');

var baseUrl = 'https://domain.tld';

module.exports = function(req, res, next)
{
  delete req.headers['host']
  var options = {
    method: req.method,
    url: baseUrl + req.url,
    headers: req.headers
  };
  if(req.headers['content-type'] == 'application/x-www-form-urlencoded') {
    options['form'] = req.body;
  }
  else {
    options['body'] = req.body;
  }

  request(options, function(error, response, body)
  {
    console.log(body);
    if (error)
    {
      throw new Error(error);
    }
  }).pipe(res);
}
```

### CODE REVIEW

**Comment by SandyChapman** [comment]
Looks like I have some tests I'll need to adjust my changes to.

**Comment by whitlockjc** [comment]
I'm interested in merging this and here is my feedback:

* Run `gulp` to run the test suite and to also lint the code *(I see some code that might trigger lint errors)*
* Squash the commits into one commit
* Add a test that shows this specific feature in action

Thanks for your help.

**Comment by SandyChapman** [comment]
@whitlockjc : I'm not getting any lint issues on the code. I've added the test coverage as requested. Please let me know if there are any further changes required.

**Comment by whitlockjc** [comment]
I really appreciate your help, thanks a lot!

**Comment by SandyChapman** [comment]
@whitlockjc : I'm happy to contribute. You merging this saves me from having to maintain a fork :+1:

**Pull request merged**
