### PR TITLE
Feature/ui hide apikey ui init oauth

### PR DESCRIPTION
**Pull request by pward123**
See https://github.com/apigee-127/swagger-tools/issues/92

Add options to hide the api-key field and add oath initialization options to swaggerUi

### CODE REVIEW

**Comment by whitlockjc** [comment]
Having never used swagger-ui with OAuth, how reusable is your implementation?  I realize that you're basically just hijacking the approach I took to have swagger-ui _infer_ API details from the server, which would make sense for your stuff as well, but could someone else use this new feature without needing to have a custom version or another pull request?

**Comment by pward123** [comment]
Without this PR, it's impossible to use oauth without forking because there is no other way to add the appName, clientId and realm.

This PR only addresses Swagger spec 2.0. I'm not using the 1.2 spec in any of my applications currently, so I didn't get a chance to look at that,

I'm fairly new to oauth and only tested this with my own oauth server based on https://www.npmjs.com/package/node-oauth2-server. I had to patch that package to support implicit (upstream swagger-ui only supports implicit).  I've used Auth0 (not with swagger-tools) and believe this would work fine for it as well.

Personally, I think most real-world applications are going to need to fork the the UI anyway. For a super simple example, there's currently there's no way to replace the swagger logo and link in the header without forking.

**Comment by whitlockjc** [comment]
I agree.  I'll merge this in Monday when I'll be able to add 1.2 support and some unit tests.  I'll also go ahead and add an issue to support using cuat builds of swagger - ui.

**Comment by whitlockjc** [comment]
I've created the issue to allow custom swagger-ui assets to be deployed as part of the swagger-ui middleware.  It's issue #111.

**Comment by whitlockjc** [comment]
Do you think if that feature were here you'd still have created this pull request?

**Comment by pward123** [comment]
#111 should address the issue

**Pull request closed without merging**
