### PR TITLE
Add support for Typescript

### PR DESCRIPTION
**Pull request by rjnienaber**
I've been using the project with this change for over a month now and it's been the only one I've had to make.

### CODE REVIEW

**Comment by liviuignat** [comment]
ping @here @whitlockjc @theganyo . What is the problem with merging this? We've been trying to use it with `typescript` also and it seems that this actually fixes the problem.

Also, why would this `var jsFileRegex = /\.(coffee|js)$/;` even be required? Shouldn't it actually accept any file extension? You never know what preprocessor will be out in some weeks?

Thanks.

**Comment by theganyo** [comment]
I don't see an issue with this.

**Comment by liviuignat** [comment]
Cool, thx :)

**Comment by whitlockjc** [comment]
The reason the `jsFileRegex` is there was to allow you to mix different sources together but only process the JavaScript _(at the time)_ ones.

**Comment by liviuignat** [comment]
When do you guys think this will be released to `npm` (roughly)? If we reference it with a git hash reference, we cannot use Docker `node-alpine` or `node-slim` base images anymore because they don't have git installed.

**Comment by whitlockjc** [comment]
I'm not sure yet.  I'm sure you can work around it but I realize this isn't ideal.

**Pull request merged**
