### PR TITLE
Allow middleware parsers options override

### PR DESCRIPTION
**Pull request by gcoupelant**
With the upgrade to multer 1.x, if you want to use `diskStorage` instead of `memoryStorage`, you can no longer just add a global multer on all routes before swagger-tools/middleware, since `multer#fields` need all parameter names.

I think that in most case, only the multer part will be used, but why not allow customization of the other parsers ?

### CODE REVIEW

**Comment by gcoupelant** [comment]
You can still use old version of multer to do the trick, but new is always better :)

**Comment by whitlockjc** [comment]
The dependent middleware that swagger-tools ships with is merely a convenience for those that want to spin up a server as quickly as possible.  And while the default configurations will work for many APIs, especially during development, the suggested practice is to configure your middlewares outside of swagger-tools.  I'm reluctant to accept this PR because it violates the architectural decisions mentioned above but let me think about it before I make a decision.

I've thought about doing this a number of times but kept going back to the original decision that if you need custom middleware or a custom configuration, it's up to the server owner to install/configure the middlewares as necessary.  Let me get back to you.

**Comment by matthewspivey** [comment]
This architectural decision clarifies things. Parsing, routing, and validation are valuable features, that seem to be generic enough for a reusable implementation. What is your vision? Should we start building thin middleware using your [apigee-127/sway](https://github.com/apigee-127/sway) project?

**Comment by whitlockjc** [comment]
Sway is the future for sure and I will be creating swagger-tools middleware replacement built on Sway for Swagger 2.0 but that should have no impact on this.  I'm still maintaining swagger-tools where possible, as in supporting things and fixing things that do not require an internal rewrite.

That being said, the issue with this PR is that while it's useful, it's against the original architecture.  The original architecture for swagger-tools was to provide parsers for use when the server author neglected to provide them.  This was to ensure that swagger-tools _"just worked"_.  It was never intended that the included parsers would be extendable or configurable.  The reason being is that swagger-tools should have no impact in your server and once I enable this, swagger-tools now owns your body/query/... parsers and I just didn't want that to be the case.  I wanted to have fallbacks but for production, I wouldn't expect people to use the embedded stuff because it's not finely tuned for your API, nor could it be.

So I need to make a decision.  To be honest, I'm not against accepting this PR as I can see the benefit that this would provide.  I just wanted to think before I just did it.  Make sense?

**Comment by whitlockjc** [comment]
Assuming I accept this, do you mind updating the PR to also allow options for `qs`?

/cc @gcoupelant

**Comment by whitlockjc** [comment]
We also might revisit the options structure naming but for now, let's get it updating for the `qs` parser and make a final decision on supporting this.  I'm leaning toward supporting it because it doesn't hurt anything nor does it change anything architecturally, because someone could still install/configure their own parser middleware like they could now.

**Comment by whitlockjc** [comment]
Once the PR is updated, I will make a decision within 24 hours so ping me if I've not responded.

**Comment by gcoupelant** [comment]
I agree on the fact that I should have my own implementation in production.

And for the options structure naming, there should be more explicit names :)

**Comment by matthewspivey** [comment]
This will address the concern of #326.

**Comment by jgranstrom** [comment]
Is there any update on this matter? I'm in the need of configuring the size limits of POST requests. Is the recommendation as of now to use the features presented in the PR, or to go about differently with integrating with swagger relating to the discussion above? @whitlockjc

**Comment by whitlockjc** [comment]
I think it's best if you just wire up the middlewares manually outside of swagger-tools.  I don't think swagger-tools wants to get into the business of owning your server runtime requirements.  *(I realize this is probably unexpected since swagger-tools ships with these runtime requirements as a convenience but that was to make the out of the box experience super simple.)*  All body/query parsing middlewares in swagger-tools are written to only use the included parsing middlewares if necessary so if you setup your own multer for `req.files`, the included one will not run.

I think it's best swagger-tools not do this and now that I've kind of drawn the line in the sand, what are your thoughts?

**Comment by jgranstrom** [comment]
I agree, better then to keep it separated from requirements of production configurations to avoid confusion.

**Comment by whitlockjc** [comment]
I'm going to close this since we're in agreement.  If you run into any troubles, want advice or what not, please file an issue and I will respond.  Thanks for your help, I really appreciate it.

**Pull request closed without merging**
