### PR TITLE
Add option to pass controllersNamesRegEx

### PR DESCRIPTION
**Pull request by GiladShoham**

### CODE REVIEW

**Comment by whitlockjc** [comment]
Could you include some form of unit test?  I'll fix the TravisCI issue shortly as that is not your fault.

**Comment by GiladShoham** [comment]
i will try to write some unit test in a few days.
i just make another improvement, so i will make another pull request soon.

**Comment by whitlockjc** [comment]
Thank you.

**Comment by whitlockjc** [comment]
We would need a unit test to get this included.  Can you also give me an example of why you'd want such a feature?

**Pull request closed without merging**
