### PR TITLE
Fix for tests that fail when run on Windows

### PR DESCRIPTION
**Pull request by Merlin-Taylor**
Fixes for the issues reported in #441

### CODE REVIEW

**Comment by whitlockjc** [comment]
Tests are failing because you've prefixed the CLI test command with `node`.  Do you mind looking into this?

**Comment by chadxz** [comment]
setting the `env` option of exec is clobbering the rest of the environment that would normally be passed. You probably want to do something like `childEnv = _.assign(process.env, { RUNNING_SWAGGER_TOOLS_TESTS: true });` then pass that to exec like `exec(cmd, { env: childEnv }, ...)`

**Comment by chadxz** [comment]
```diff
diff --git a/test/helpers.js b/test/helpers.js
index c6c0db2..85ccf9b 100644
--- a/test/helpers.js
+++ b/test/helpers.js
@@ -146,9 +146,9 @@ module.exports.executeCLI = function (args, done) {
   // Add Node args
   args.unshift('node', path.resolve(path.join(__dirname, '..', 'bin', 'swagger-tools')));
   var options = {
-    env: {
+    env: _.assign({}, process.env, {
       RUNNING_SWAGGER_TOOLS_TESTS: true
-    }
+    })
   };
   cp.exec(args.join(' '),  options, function (err, stdout, stderr) {
     done(stderr, stdout);
```

**Comment by whitlockjc** [comment]
Thanks a lot.

**Pull request merged**
