### PR TITLE
fix: package.json to reduce vulnerabilities

### PR DESCRIPTION
**Pull request by andrewshawcare**

### CODE REVIEW

**Comment by whitlockjc** [comment]
Do you mind running `gulp` to ensure the tests pass?

**Comment by andrewshawcare** [comment]
I see gulp running in Travis, do you want me to run it locally and paste the results?

**Comment by whitlockjc** [comment]
Actually, I think you're probably fine.  All you did was update deps and those deps are server-side only so the `gulp` process isn't necessary beyond that.  _(The reason I asked is if you touched any code that changed the non-middleware stuff, there would be build artifacts generated via `gulp` that would need to be checked in.)_

**Comment by andrewshawcare** [comment]
No worries, I ran locally and things passed. If you want I can copy the console output.

**Comment by whitlockjc** [comment]
I appreciate you taking the time to look into this.

**Comment by caleb0199** [comment]
Looking forward to this getting released. Thanks for making/including this change.

**Comment by whitlockjc** [comment]
I finished the `json-refs` rewrite last night, finishing up tests as we speak and will release that ASAP.  As soon as that's done, `swagger-tools` and `sway` will get the update treatment as well.

**Comment by osher** [comment]
@whitlockjc 
When is this change planned to be published? I see in npm last release `about a year ago`

**Pull request merged**
