### PR TITLE
Update schemas

### PR DESCRIPTION
**Pull request by ddm**
Update the READMEs to point to the latest schemas from https://github.com/swagger-api/swagger-spec

### CODE REVIEW

**Comment by ddm** [comment]
Sorry for breaking the build. I'm looking into it...

**Comment by whitlockjc** [comment]
Your commit only covers a single change to the JSON Schema file.  I have gone ahead and updated the Swagger 2.0 JSON Schema file in this project.  You can see the pertinent changes to the JSON Schema file here: https://github.com/apigee-127/swagger-tools/commit/79d72c1615ca4c6031c2a41fa507fc750bcdcfb2#diff-6

**Comment by ddm** [comment]
Yes I actually reverted the schema update when I realised that it broke the tests.
I left only the "brackets" value because it is really useful for projects using the jQuery "traditional" ajax option.
https://api.jquery.com/jquery.param/

**Comment by whitlockjc** [comment]
The problem is the Swagger schemas are basically imported/copied from [swagger-api/swagger-spec](https://github.com/swagger-api/swagger-spec) so they must match.  The drift between swagger-spec and swagger-tools was due to recent changes.

**Comment by ddm** [comment]
Is the a way I can add the "brackets" value to collectionFormat in another pull request?

It is now supported by swagger-ui:
https://github.com/swagger-api/swagger-js/issues/191
https://github.com/swagger-api/swagger-js/commit/30eb4f30af13df59ca58baedf310ccfc66f18835

We use it to support older jQuery clients (that cannot be updated) and swagger-tools throws an error at our swagger.json definition because of it...

**Comment by whitlockjc** [comment]
I cannot as I do not own the Swagger 2.0 JSON Schema files.  I simply just use what is provided here by swagger-api/swagger-spec: [https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json).

I have commented on [https://github.com/swagger-api/swagger-js/issues/191](swagger-api/swagger-js/issues/191) to let @fehguy know of the conflict but if `brackets` is indeed a supported `collectionFormat`, the Swagger 2.0 JSON Schema files and related Swagger 2.0 Specification Documentation need to be updated.  This would require an issue to be filed in swagger-api/swagger-spec.

**Comment by ddm** [comment]
Right, I understand the need to stay in sync with the swagger-spec schema. Otherwise you would have to maintain the change across new versions of the schema. I'll try to get it into the swagger-spec 2.0 schema too...

**Comment by whitlockjc** [comment]
I'm having a discussion on [swagger-api/swagger-js/issues/191](https://github.com/swagger-api/swagger-js/issues/191) right now regarding this.  Feel free to chime in.

**Comment by ddm** [comment]
Indeed :)

**Comment by ddm** [comment]
FYI I have to get this working immediately so I made a temporary fork here: https://www.npmjs.com/package/swagger-tools-with-brackets

Hopefully I can deprecate it soon. I'll continue the discussion on https://github.com/swagger-api/swagger-js/issues/191 and try to push for the inclusion of the 'brackets' serialisation format.

On another note, does swagger-tools currently check for enums in the validators?

**Pull request closed without merging**
