### PR TITLE
should not throw an error for empty responses that validate void

### PR DESCRIPTION
**Pull request by bitcloud**
if you have an empty result with statusCode 200 it throws an error

### CODE REVIEW

**Comment by whitlockjc** [comment]
Your test is checking that `''` passes `type: void` responses but a valid `void` response is no response, as in no body at all.  So you're wanting an empty string to be treated the same as no response?

**Comment by bitcloud** [comment]
the problem comes from the response validator. it throws an error if I do res.end() and the response should be void, because it treats writtenData as true even if it has the length 0.

It ends up as an empty string in the response because the body is empty and http doesn't transfer types in an plain text channel. so after requesting it via http it is just an empty string then :)

**Comment by whitlockjc** [comment]
I get it now.  Let me review.

**Comment by whitlockjc** [comment]
Thanks.

**Pull request merged**
