### PR TITLE
Validate operation's tags

### PR DESCRIPTION
**Pull request by IvanGoncharov**
validate that tags declared

### CODE REVIEW

**Comment by whitlockjc** [comment]
To make sure I understand this properly, this validation just makes sure that tag references in operations correspond to a declared tag at the global level?

**Comment by IvanGoncharov** [comment]
Yes

**Comment by IvanGoncharov** [comment]
Actually according to Swagger spec:
> Not all tags that are used by the Operation Object must be declared.
So I probably need to do this as warning.
And generate it only if `tags` exist and not empty
@whitlockjc What do you think?

**Comment by mohsen1** [comment]
Yup, you can have tags without any root level tag definition

**Comment by IvanGoncharov** [comment]
If person already put something into global `tags`, he meant to declare all tags.
I see two possible mistakes with tag names:
 - misspell tag name
 - user forget to add it into global `tags`

**Comment by whitlockjc** [comment]
If Swagger does not require it, swagger-tools likely shouldn't either.  We already have started breaking out the API behind validation/... into [apigee-127/sway](https://github.com/apigee-127/sway) and that library already has the ability to register custom validators.  swagger-tools likely will not be updated to use sway but going forward, all of our middlewares/frameworks/... will be updated to use sway.

I'll keep this open while others chime in.

/cc @webron

**Comment by webron** [comment]
It's definitely not an error. As for a warning, I guess that's tool-dependent. There's nothing technically wrong with not declaring it at the top level. The top level serves as additional meta-data and if someone chooses not to include, that is absolutely fine.

**Comment by whitlockjc** [comment]
I'm closing this based on @webron's feedback.  Since swagger-node and swagger-editor are now using [sway](https://github.com/apigee-127/sway) and sway has customizable validators, I'm going to point you in that direction if you want to validate Swagger with custom validation.

**Pull request closed without merging**
