### PR TITLE
fix: incorrectly traversing of object with length property

### PR DESCRIPTION
**Pull request by argos83**
@whitlockjc Swagger-tools had the same bug than json-refs (lodash .each behavior on objects with a length property)  https://github.com/whitlockjc/json-refs/pull/129

this PR:
  * fixes the buggy use of .each on objects
  * pins the json-ref dependency to the fixed version
  * includes a test that will pass right away when the fix is in place or will timeout and fail if there's ever a regression (I couldn't find a more direct way of testing this fix using the public api)

### CODE REVIEW

**Comment by argos83** [comment]
CLA signed (I couldn't find a mention to this CLA thing in the contributors guide)

**Comment by argos83** [comment]
CLA signed again with my other email address

**Comment by BenSayers** [comment]
@whitlockjc is there anything blocking this PR from being merged? It's a small bugfix and has been well tested.

**Comment by BenSayers** [comment]
@whitlockjc thanks for merging. Can you please release this so we can consume the fix?

**Comment by whitlockjc** [comment]
I'll see what I can do.

**Comment by BenSayers** [comment]
@whitlockjc bump

**Pull request merged**
