### PR TITLE
fix issue with express 4.x issuing 304 on unmodified response

### PR DESCRIPTION
**Pull request by theganyo**
originally reported here: https://github.com/swagger-api/swagger-node/issues/266

### CODE REVIEW

**Comment by whitlockjc** [comment]
Any reason why we didn't just check for `req.fresh != true`?

**Comment by theganyo** [comment]
Nope.

**Comment by whitlockjc** [comment]
Actually, let's just use your approach and use the same logic Express does: https://github.com/strongloop/express/blob/f73ff9243006ea010fffdaa748f06df3a5b986e7/lib/response.js#L192  They will remove the `Content-Type` header for `204` and `304`.

**Comment by theganyo** [comment]
Sure. I decided not to mess with 204s myself, but have at it if you feel it's appropriate. :)

**Comment by whitlockjc** [comment]
Thanks Scott.

**Comment by am17torres** [comment]
Hey thanks for taking care of this so quickly. Is there going to be a version bump in npm?

**Comment by whitlockjc** [comment]
Yes, I'll get a new *(`0.9.1`)* release out today.

**Pull request merged**
