### PR TITLE
update superagent, supertest, and commander dependencies

### PR DESCRIPTION
**Pull request by wickedest**
The swagger-tools were failing retirejs dependency checks because it was using an out of date superagent and supertest, which had a local, insecure version of jquery.  This has been fixed in later versions, so I updated the dependencies.  Also fixed unit tests that were failing because of a change in `commander` that changed the help usage.  Also updated run-sequence.

*NOTE*: this builds/passes but older versions warn about incompatible node versions.

### CODE REVIEW

**Comment by whitlockjc** [comment]
Thanks for the PR.  I'll get to it shortly.

**Comment by alasdairhurst** [comment]
@whitlockjc  Had a chance to look yet?

**Comment by whitlockjc** [comment]
Sorry about the delay, I need to do a security patch release.  I'll do that today and it will include these changes.

**Comment by rcarroll380** [comment]
Any update on this PR? Superagent needs to be at 3.6.1 now because of vulnerability with https://nodesecurity.io/advisories/535

**Comment by wickedest** [comment]
Thanks for merging this.  @whitlockjc, did you cut a release?  The version is still at 0.10.1.

**Comment by gobeyboy** [comment]
@whitlockjc Jeremy, any kind of update or ETA on the patch release would be gratefully appreciated.

**Comment by elankeeran** [comment]
@whitlockjc Could you; please update the ETA otherwise we need to look for alternative solution.

**Comment by whitlockjc** [comment]
I'll try to get this done this week but I've said that before.  Feel free to help out.

**Comment by whitlockjc** [comment]
Thanks a ton @wickedest!

**Pull request merged**
