### PR TITLE
Exclude spec|test.js files from swagger-router

### PR DESCRIPTION
**Pull request by morgs32**
I have some spec files along with the controller files in my controller directory. I should be able to ignore certain type of files.

Solves issue: #354

### CODE REVIEW

**Comment by morgs32** [comment]
Signed CLA

**Comment by whitlockjc** [comment]
I'd much rather see this as a router middleware option so that we don't assume this naming convention for everyone.  Thoughts?

**Comment by morgs32** [comment]
I think that's a good idea. Something like an `exclude` prop that takes an array of regex's?

**Comment by morgs32** [comment]
@whitlockjc how about this? Gimme the thumbs up and I'll make one more commit to docs

**Comment by whitlockjc** [comment]
How about you do it because it's the right thing to do?  👍   _(That was said in a joking tone.)_

I'll give this a review.

**Comment by morgs32** [comment]
@whitlockjc bump

**Pull request closed without merging**
