### PR TITLE
Allow json body-parser options to be passed to swagger-metadata

### PR DESCRIPTION
**Pull request by ben-moore**
We hit an issue where we could not submit a JSON request larger than 100kb, due to the default size limits on body-parser.  This change adds options to swagger-metadata which allow you to specify configuration options for the JSON parser so that you can override this or any other body-parser settings.

### CODE REVIEW

**Comment by whitlockjc** [comment]
This is a duplicate of #263 and #322.  Long story short, swagger-tools includes the parser middlewares it does as a convenience so it works out of the box.  But they are conditionally loaded if they are not already loaded.  This means if you want to customize the parser middlewares, you can do this by using the appropriate middleware with the configuration you deem fit without swagger-tools being involved.

For more detail on why this was done this way, please read the linked issues.

**Comment by ben-moore** [comment]
@whitlockjc thanks for the feedback.  Completely agree regarding the responsibilities not being right, we had body-parser wired up in our own stack but were still hitting the issue, hence the PR.  I hadn't appreciated the conditional loading, so it must be an issue with the order in which we're applying modules.  I'll take another look.

**Comment by whitlockjc** [comment]
Let me look at the PR because if you're fixing a bug, that's different.  I assumed it was just a repeat of previous requests.

**Comment by whitlockjc** [comment]
Here is the code where we check if we need to use an internal parser: https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-metadata.js#L135  If you see something in there that is returning a false positive, let me know and we'll fix it.  Or submit a PR of course. 👍

**Comment by ben-moore** [comment]
Ok, thanks.  From your description it sounds like it may be a duplicate though, and I would certainly prefer to have this control all in our stack so will definitely look again at the cause - feels like it might be a sequencing issue, with swagger being applied before (our) body-parser.

**Comment by whitlockjc** [comment]
Gotcha.  I'm sure you already know but just in case: All parsers should be registered **prior** to the Swagger middlewares.  If something is mucking with that order, this could be the case.  Of course, there could be a logic issue in code so do not assume swagger-tools is right.  :)

**Pull request closed without merging**
